services:
  - type: web
    name: expense-tracker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerBuildArgs:
      - key: VITE_FIREBASE_API_KEY
        fromEnv: VITE_FIREBASE_API_KEY
      - key: VITE_FIREBASE_AUTH_DOMAIN
        fromEnv: VITE_FIREBASE_AUTH_DOMAIN
      - key: VITE_FIREBASE_PROJECT_ID
        fromEnv: VITE_FIREBASE_PROJECT_ID
      - key: VITE_FIREBASE_STORAGE_BUCKET
        fromEnv: VITE_FIREBASE_STORAGE_BUCKET
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        fromEnv: VITE_FIREBASE_MESSAGING_SENDER_ID
      - key: VITE_FIREBASE_APP_ID
        fromEnv: VITE_FIREBASE_APP_ID
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://expense-tracker-1-0mg2.onrender.com
      - key: ASSET_URL
        value: https://expense-tracker-1-0mg2.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker
    plan: free
